name: CI

# 定义触发工作流的条件
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/roothide/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      - name: Prepare Theos
        uses: huami1314/theos-action@main

      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1
          make package THEOS_PACKAGE_SCHEME=roothide FINALPACKAGE=1
          ls -la packages/

      # 上传所有 deb 包作为一个压缩文件
      - name: Upload All Deb packages
        uses: actions/upload-artifact@v4.3.3
        with:
          name: DYYY-All
          path: packages/*.deb
          if-no-files-found: error

      # 单独上传普通版本
      - name: Upload Normal Version
        uses: actions/upload-artifact@v4.3.3
        with:
          name: DYYY-Normal
          path: packages/*[0-9].deb
          if-no-files-found: error

      # 单独上传 rootless 版本
      - name: Upload Rootless Version
        uses: actions/upload-artifact@v4.3.3
        with:
          name: DYYY-Rootless
          path: packages/*rootless*.deb
          if-no-files-found: warn

      # 单独上传 roothide 版本
      - name: Upload Roothide Version
        uses: actions/upload-artifact@v4.3.3
        with:
          name: DYYY-Roothide
          path: packages/*roothide*.deb
          if-no-files-found: warn
